trigger:
- development

variables:
  tag: $(Build.BuildId)
  imageRepository: frontend
  dockerfilePath: $(Build.SourcesDirectory)/Dockerfile
  containerRegistry: bouacr.azurecr.io   # ACR login server

stages:
- stage: Build
  displayName: Build & Push Stage
  jobs:
  - job: Build
    displayName: Build Job
    pool:
      vmImage: ubuntu-latest
    steps:
    # 1️⃣ Setup Docker Buildx
    - script: |
        docker run --privileged --rm tonistiigi/binfmt --install all
        docker buildx create --use --name mybuilder
        docker buildx inspect --bootstrap
      displayName: Setup Buildx

    # 2️⃣ Build & Push (using bouacr-sc for login automatically)
    - task: Docker@2
      displayName: Build and Push Frontend
      inputs:
        command: buildAndPush
        containerRegistry: bouacr-sc       # ✅ ACR service connection
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        arguments: --platform linux/amd64
        tags: |
          $(tag)
          latest

- stage: Deploy
  displayName: Deploy Stage
  dependsOn: Build
  jobs:
  - deployment: DeployFrontend
    displayName: Deploy Frontend
    environment: 'aks-frontend'   # optional, for approvals
    pool:
      vmImage: ubuntu-latest
    strategy:
      runOnce:
        deploy:
          steps:
          - task: Kubernetes@1
            displayName: Set image in deployment
            inputs:
              connectionType: 'Azure Resource Manager'
              azureSubscriptionEndpoint: 'bougroup'      # ✅ Your AKS service connection
              azureResourceGroup: 'bougroup'
              kubernetesCluster: 'bouaks'
              namespace: frontend
              command: set
              arguments: image deployment/frontend frontend=bouacr.azurecr.io/$(imageRepository):$(tag)

