trigger:
- development

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: frontend

steps:
- task: Checkout@1
  displayName: 'Checkout Code'

- task: Docker@2
  displayName: 'Build and Push Frontend'
  inputs:
    command: buildAndPush
    repository: $(imageName)
    dockerfile: Dockerfile
    containerRegistry: bouacr-sc
    arguments: --platform linux/amd64
    tags: |
      $(Build.BuildId)
      latest

# 3️⃣ Deploy to AKS
- task: KubernetesManifest@1
  displayName: 'Deploy Frontend'
  inputs:
    action: deploy
    connectionType: kubernetesServiceConnection
    kubernetesServiceConnection: bouaks-sc
    namespace: frontend
    manifests: |
      k8s/frontend.yaml
    containers: |
      bouacr.azurecr.io/$(imageName):$(Build.BuildId)
