trigger:
- development

variables:
  tag: $(Build.BuildId)
  imageRepository: frontend
  dockerfilePath: $(Build.SourcesDirectory)/Dockerfile
  containerRegistry: bouacr.azurecr.io   # ACR login server

stages:
- stage: Build
  displayName: Build & Push Stage
  jobs:
  - job: Build
    displayName: Build Job
    pool:
      vmImage: ubuntu-latest
    steps:
    # 1️⃣ Setup Docker Buildx
    - script: |
        docker run --privileged --rm tonistiigi/binfmt --install all
        docker buildx create --use --name mybuilder
        docker buildx inspect --bootstrap
      displayName: Setup Buildx

    # 2️⃣ Build & Push (using bouacr-sc for login automatically)
    - task: Docker@2
      displayName: Build and Push Frontend
      inputs:
        command: buildAndPush
        containerRegistry: bouacr-sc       # ✅ ACR service connection
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        arguments: --platform linux/arm64
        tags: |
          $(Build.BuildId)
          latest

- stage: Deploy
  displayName: Deploy to AKS
  dependsOn: Build
  jobs:
  - job: Deploy
    steps:
    # 1️⃣ Replace tag placeholder in manifest
    - script: |
        sed -i "s|__TAG__|$(Build.BuildId)|g" k8s/frontend.yml
        echo "Updated image tag in manifest:"
        cat k8s/frontend.yml
      displayName: Update image tag in manifest

    # 2️⃣ Apply manifest to AKS
    - task: Kubernetes@1
      displayName: Deploy to AKS
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscriptionEndpoint: 'bougroup'    # ✅ AKS service connection
        azureResourceGroup: 'bougroup'
        kubernetesCluster: 'bouaks'
        namespace: frontend
        command: apply
        useConfigurationFile: true
        configuration: $(Build.SourcesDirectory)/k8s/frontend.yml

