trigger:
- development

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: frontend
  acrName: bouacr.azurecr.io

steps:
- checkout: self

- task: Docker@2
  displayName: Login to ACR
  inputs:
    command: login
    containerRegistry: bouacr-sc

- script: |
    echo "Creating buildx builder..."
    docker buildx create --use
    echo "Building and pushing image..."
    docker buildx build \
      --platform linux/amd64 \
      -t $(acrName)/$(imageName):$(Build.BuildId) \
      -t $(acrName)/$(imageName):latest \
      -f Dockerfile . \
      --push
  displayName: Build and Push Frontend

- task: KubernetesManifest@1
  displayName: Deploy Frontend
  inputs:
    action: deploy
    connectionType: kubernetesServiceConnection
    kubernetesServiceConnection: bouaks-sc
    namespace: frontend
    manifests: |
      k8s/frontend.yml
    containers: |
      $(acrName)/$(imageName):$(Build.BuildId)
