trigger:
- development

variables:
  acrLoginServer: bouacr.azurecr.io

stages:
- stage: Build
  displayName: Build and Push Docker Image
  jobs:
  - job: BuildPush
    pool:
      vmImage: ubuntu-latest
    steps:
    - checkout: self

    - task: Docker@2
      displayName: Build and Push Frontend
      inputs:
        command: buildAndPush
        repository: frontend
        dockerfile: Dockerfile
        buildContext: .
        containerRegistry: bouacr-sc    # 👈 Docker Registry Service Connection
        tags: |
          latest
          $(Build.BuildId)

- stage: Deploy
  displayName: Deploy to AKS
  dependsOn: Build
  jobs:
  - job: DeployK8s
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: AzureCLI@2
      displayName: Set AKS Context
      inputs:
        azureSubscription: 'bougroup'   # 👈 azurerm service connection
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az aks get-credentials --resource-group bougroup --name bouaks --overwrite-existing

    - task: KubernetesManifest@1
      displayName: Deploy Frontend
      inputs:
        action: deploy
        kubernetesServiceConnection: bouaks-sc   # 👈 Kubernetes Service Connection
        namespace: frontend
        manifests: |
          $(Build.SourcesDirectory)/k8s/frontend.yaml
        containers: |
          $(acrLoginServer)/frontend:$(Build.BuildId)
