trigger:
- development   # change to your branch name

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageRepository: 'frontend'
  containerRegistry: 'bouacr.azurecr.io'
  dockerfilePath: 'Dockerfile'
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build and Push
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      displayName: Build and Push Frontend
      inputs:
       command: buildAndPush
       repository: $(imageRepository)
       dockerfile: $(dockerfilePath)
       containerRegistry: bouacr-sc    # ✅ ACR service connection
       arguments: --platform linux/arm64
       tags: |
        $(tag)
        latest

- stage: Deploy
  displayName: Deploy to AKS
  dependsOn: Build
  jobs:
  - job: Deploy
    displayName: Deploy
    steps:
    - task: AzureCLI@2
      displayName: Login to AKS
      inputs:
        azureSubscription: 'bougroup'   # ✅ AzureRM connection for AKS login
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az aks get-credentials -g bougroup -n bouaks --overwrite-existing

    - task: KubernetesManifest@1
      displayName: Deploy Frontend
      inputs:
        connectionType: 'kubernetesServiceConnection'
        kubernetesServiceConnection: 'bouaks-sc'   # ✅ Kubernetes service connection
        namespace: frontend
        manifests: |
          k8s/frontend.yml
        containers: |
          $(containerRegistry)/$(imageRepository):$(tag)
