trigger:
- development

pool:
  vmImage: 'ubuntu-latest'

variables:
  ACR_NAME: bouacr
  IMAGE_NAME: frontend
  NAMESPACE: frontend

stages:
- stage: Build
  displayName: Build and Push Image
  jobs:
  - job: DockerBuild
    steps:
    - task: DockerInstaller@0
      displayName: Install Docker CLI

    - script: |
        echo "Logging into ACR..."
        az acr login --name $(ACR_NAME)

        echo "Creating buildx builder..."
        docker buildx create --use --name mybuilder || true

        echo "Building and pushing image..."
        docker buildx build \
          --platform linux/amd64 \
          -t $(ACR_NAME).azurecr.io/$(IMAGE_NAME):latest \
          -t $(ACR_NAME).azurecr.io/$(IMAGE_NAME):$(Build.BuildId) \
          --push .
      displayName: Build & Push Docker Image

- stage: Deploy
  displayName: Deploy to AKS
  dependsOn: Build
  jobs:
  - job: K8SDeploy
    steps:
    - task: KubernetesManifest@1
      displayName: Deploy Frontend
      inputs:
        action: deploy
        kubernetesServiceConnection: bouaks-sc
        namespace: $(NAMESPACE)
        manifests: |
          k8s/frontend.yaml
        containers: |
          $(ACR_NAME).azurecr.io/$(IMAGE_NAME):$(Build.BuildId)
