apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  namespace: frontend
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: app.bouapps.xyz
      http:
        paths:
          # Frontend React app
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80

          # Backend Strapi API (cross-namespace call)
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: strapi-service
                port:
                  number: 1337

          # Optional: Strapi Admin panel
          - path: /admin
            pathType: Prefix
            backend:
              service:
                name: strapi-service
                port:
                  number: 1337
